apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    component: messaging
    version: "1.1.0"
spec:
  ports:
  - name: dist
    port: 25672
  - name: management
    port: 15672
  - name: amqp
    port: 5672
  - name: epmd
    port: 4369
  selector:
    app: rabbitmq
    component: messaging
    version: "1.1.0"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    component: messaging
    version: "1.1.0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq
      component: messaging
      version: "1.1.0"
  template:
    metadata:
      labels:
        app: rabbitmq
        component: messaging
        version: "1.1.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: rabbitmq
        image: registry.hub.docker.com/library/rabbitmq:3.8-rc-management-alpine
        # resources:
        #   requests:
        #     memory: "100M"
        #     cpu: "100m"
        #   limits:
        #     memory: "250M"
        #     cpu: "250m"
        ports:
        - name: dist
          containerPort: 25672
        - name: management
          containerPort: 15672
        - name: amqp
          containerPort: 5672
        - name: epmd
          containerPort: 4369
        imagePullPolicy: Always #IfNotPresent
