# https://github.com/istio/istio/blob/44798c747a5a4483bafc810c35e568494d78cc99/install/kubernetes/helm/istio/README.md
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
data:
  passphrase: MWYyZDFlMmU2N2Rm
  username: YWRtaW4=
type: Opaque
